spring:
    application:
        name: Smart Contact Manager
    datasource:
        url: jdbc:mysql://localhost:3306/smart_contact_manager
        username: root
        password: supersection
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update


server:
    port: 8081